name: Destroy Spot VM and Reattach EIP
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: linkedin-spot-vm

    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            us-east-1

    - uses: hashicorp/setup-terraform@v2

    - name: Destroy & return EIP
      run: ./destroy.sh

    - name: Delete state file from repo
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name  "github-actions"

        git rm -f terraform.tfstate || true
        if [ -f terraform.tfstate.backup ]; then
          git rm -f terraform.tfstate.backup || true
        fi

        git commit -m "CI: remove terraform state $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "Nothing to delete"
        git push

