name: Provision LinkedIn Spot VM
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  provision:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: linkedin-spot-vm

    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            us-east-1

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform init & apply
      run: |
        terraform init -input=false
        terraform apply -auto-approve

    - name: Commit state file
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name  "github-actions"

        # always add the main state file
        git add -f terraform.tfstate

        # add the backup only if it exists
        if [ -f terraform.tfstate.backup ]; then
          git add -f terraform.tfstate.backup
        fi

        git commit -m "CI: save terraform state $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
        git push

