name: Provision LinkedIn Spot VM
on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: linkedin-spot-vm

    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            us-east-1

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform init & apply
      run: |
        terraform init -input=false
        terraform apply -auto-approve

    - name: Commit state file
      run: |
        git config user.email "github-actions@example.com"
        git config user.name  "github-actions"
        git add terraform.tfstate terraform.tfstate.backup
        git commit -m "CI: add terraform state for LinkedIn VM run $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        git push
